In [25]:
from database.db_tests import DBConn
import pandas as pd

In [50]:
pf = DBConn()
pf = pf.DATABASE['fixture_players_stats']

In [33]:
cursor = pf.aggregate([{
            '$match':{
                'seasonId':363
            },
        },{
            '$project':{
                '_id': 0,
                'age': 0,
                'birth': 0,
                'country': 0,
                'isoCode': 0,
                'name': 0,
                'nationalTeam': 0,
                'positionInfo': 0,
    }
}])
data = list(cursor)

In [61]:
df = pd.DataFrame(data)
df

,f_id,id,seasonId,accurate_back_zone_pass,accurate_chipped_pass,accurate_fwd_zone_pass,accurate_long_balls,accurate_pass,accurate_throws,aerial_won,...,dangerous_play,assist_own_goal,stand_save,own_goals,att_obxd_right,assist_blocked_shot,draws,assist_post,att_obx_left,att_pen_post
0,58898,8185.0,363,14.0,2.0,28.0,6.0,42.0,8.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,58898,7490.0,363,7.0,NaN,12.0,NaN,19.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,58898,5079.0,363,9.0,NaN,16.0,3.0,24.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,58898,10727.0,363,17.0,2.0,2.0,8.0,19.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,58898,11267.0,363,4.0,NaN,8.0,NaN,12.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1722,58939,4979.0,363,2.0,NaN,2.0,NaN,4.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1723,58939,52951.0,363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1724,58939,23994.0,363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1725,58939,16640.0,363,2.0,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1726,58939,2896.0,363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df.describe()

,f_id,id,seasonId,accurate_back_zone_pass,accurate_chipped_pass,accurate_fwd_zone_pass,accurate_long_balls,accurate_pass,accurate_throws,aerial_won,...,dangerous_play,assist_own_goal,stand_save,own_goals,att_obxd_right,assist_blocked_shot,draws,assist_post,att_obx_left,att_pen_post
count,1727.000000,1727.000000,1727.0,1257.000000,732.000000,1264.000000,833.000000,1304.000000,353.000000,721.000000,...,1.0,5.0,8.000000,5.0,3.0,2.0,248.0,1.0,2.0,1.0
mean,58921.426173,12986.751013,363.0,15.420048,2.375683,14.515823,3.054022,28.644939,4.572238,2.264910,...,1.0,1.0,1.125000,1.0,1.0,1.0,1.0,1.0,1.0,1.0
std,13.956777,12713.183260,0.0,14.109959,1.800474,11.895550,2.471124,21.597103,3.934986,1.802931,...,NaN,0.0,0.353553,0.0,0.0,0.0,0.0,NaN,0.0,NaN
min,58897.000000,2100.000000,363.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0
25%,58909.500000,4640.000000,363.0,5.000000,1.000000,6.000000,1.000000,13.000000,1.000000,1.000000,...,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0
50%,58921.000000,9169.000000,363.0,11.000000,2.000000,11.000000,2.000000,24.000000,3.000000,2.000000,...,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0
75%,58933.000000,14824.000000,363.0,23.000000,3.000000,20.000000,4.000000,40.000000,7.000000,3.000000,...,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0
max,58945.000000,76258.000000,363.0,106.000000,13.000000,71.000000,15.000000,126.000000,19.000000,13.000000,...,1.0,1.0,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [47]:
df = df.fillna(0)